# This docker-compose file is only for quick launch mlflow.
# Do not use in the production environment.


version: '3.6'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mlflow-service-net
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  mlflow:
    restart: always
    build: ./mlflow
    image: mlflow:2.8.0
    container_name: mlflow
    ports:
      - "5000:5000"
    networks:
      - mlflow-service-net
    volumes:
      - mlflow-volume:/mlflow/mlruns
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    command:
      - sh
      - -c
      - mlflow server 
        --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
        --default-artifact-root s3://${BUCKET_NAME} 
        --host 0.0.0.0

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - mlflow-service-net
    volumes:
      - minio-volume:${MINIO_VOLUMES}
    command: server ${MINIO_VOLUMES} --console-address ":9001"

volumes:
  mlflow-volume:
  db-volume:
  minio-volume:

networks:
  mlflow-service-net:
    external: true
