# This docker-compose file is only for quick launch mlflow.
# Do not use in the production environment.


version: '3.6'

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - type: volume
        source: db-volume
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mlflow-service-net
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}


  mlflow:
    restart: always
    build: ./mlflow
    image: mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    networks:
      - mlflow-service-net
    volumes:
      - type: volume
        source: mlflow-volume
        target: /mlflow/mlruns
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    command:
      - sh
      - -c
      - mlflow server 
        --backend-store-uri mysql+pymysql://${MARIADB_USER}:${MARIADB_PASSWORD}@db:3306/${MARIADB_DATABASE} 
        --default-artifact-root s3://${BUCKET_NAME} 
        --host 0.0.0.0

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    networks:
      - mlflow-service-net
    volumes:
      - type: volume
        source: minio-volume
        target: ${MINIO_VOLUMES}
    command: server ${MINIO_VOLUMES} --console-address ":9001"

volumes:
  mlflow-volume:
  db-volume:
  minio-volume:

networks:
  mlflow-service-net:
    external: true
